/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import projeto.BancoDeDados;
import projeto.Cliente;
import static telas.MainMenu.listaClientes;

/**
 *
 * @author user
 */
public class CadastroUser extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUser
     */
    public CadastroUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLivros = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        labelNewUsuario = new javax.swing.JLabel();
        txtNewUsuario = new javax.swing.JTextField();
        labelNewSenha = new javax.swing.JLabel();
        txtNewSenha = new javax.swing.JPasswordField();
        labelNewTelefone = new javax.swing.JLabel();
        labelNewEmail = new javax.swing.JLabel();
        txtNewEmail = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        txtNewTelefone = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BiblioTech | Cadastro");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imgs/user-icon.png")).getImage()
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        imgLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/capa-menu-livros.jpg"))); // NOI18N

        titulo.setFont(new java.awt.Font("Centaur", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("BIBLIOTECH");

        labelNewUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelNewUsuario.setText("Usuario");

        txtNewUsuario.setToolTipText("Forneça seu usuário");
        txtNewUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewUsuarioActionPerformed(evt);
            }
        });

        labelNewSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelNewSenha.setText("Senha");

        txtNewSenha.setToolTipText("Forneça sua senha");

        labelNewTelefone.setForeground(new java.awt.Color(255, 255, 255));
        labelNewTelefone.setText("Telefone");

        labelNewEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelNewEmail.setText("Email");

        txtNewEmail.setToolTipText("Forneça seu usuário");
        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(51, 164, 40));
        btnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        try {
            txtNewTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+##(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelNewEmail)
                                .addComponent(labelNewTelefone)
                                .addComponent(labelNewUsuario)
                                .addComponent(labelNewSenha)
                                .addComponent(txtNewSenha)
                                .addComponent(txtNewUsuario)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                .addComponent(txtNewTelefone)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imgLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(57, 57, 57)
                .addComponent(labelNewUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNewSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNewSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNewTelefone)
                .addGap(12, 12, 12)
                .addComponent(txtNewTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNewEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewUsuarioActionPerformed

    }//GEN-LAST:event_txtNewUsuarioActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtNewSenha.getText().equals("") || txtNewEmail.getText().equals("") || txtNewUsuario.getText().equals("") || txtNewTelefone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!", "ERRO", JOptionPane.ERROR_MESSAGE);
            txtNewUsuario.requestFocus();
        }
        else{
            String usuario = txtNewUsuario.getText();
            String senha = txtNewSenha.getText();
            String telefone = txtNewTelefone.getText();
            String email = txtNewEmail.getText();
            
            if (BancoDeDados.in(usuario, "Cliente", "User")){
                JOptionPane.showMessageDialog(null, "Usuário Inválido!", "ERRO", JOptionPane.ERROR_MESSAGE);
                txtNewUsuario.requestFocus();
            }
            else if (usuario.contains(" ")){
                JOptionPane.showMessageDialog(null, "Não utilize espaços!", "ERRO", JOptionPane.ERROR_MESSAGE);
                txtNewUsuario.requestFocus();
            }
            else{    
                String linha = usuario + " " + senha + " " + telefone + " " + email;
                String login = usuario + " " + senha;
                BancoDeDados.escrever(linha, "Cliente", "Cadastro");
                BancoDeDados.escrever(login, "Cliente", "Login");
                BancoDeDados.escrever(usuario, "Cliente", "User");
                listaClientes.add(new Cliente(usuario, senha, telefone, email));
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel imgLivros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNewEmail;
    private javax.swing.JLabel labelNewSenha;
    private javax.swing.JLabel labelNewTelefone;
    private javax.swing.JLabel labelNewUsuario;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JPasswordField txtNewSenha;
    private javax.swing.JFormattedTextField txtNewTelefone;
    private javax.swing.JTextField txtNewUsuario;
    // End of variables declaration//GEN-END:variables
}
